services:
  eventstore:
    image: ${TROGON_EVENTSTORE_IMAGE:-ghcr.io/trogonstack/trogoneventstore:ci}
    environment:
    - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=localhost
    - EVENTSTORE_ADVERTISE_NODE_PORT_TO_CLIENT_AS=2113
    - EVENTSTORE_NODE_IP=0.0.0.0
    - EVENTSTORE_START_STANDARD_PROJECTIONS=True
    - EVENTSTORE_RUN_PROJECTIONS=All
    volumes:
    - spear_eventstore:/var/lib/eventstore
    - ./eventstoredb:/etc/eventstore:ro
    # to run in insecure mode, which can be nice for debugging protobuf
    # messages via wireshark
    # command: "--insecure --run-projections=All"
    ports:
    - 2113:2113

  app:
    image: elixir:1.16.2
    depends_on:
    - eventstore
    environment:
    - 'ERL_AFLAGS=-kernel shell_history enabled'
    - EVENTSTORE_HOST=eventstore
    - EVENTSTORE_VERSION=${EVENTSTORE_VERSION:-0.0.0}
    volumes:
    - ./:/app
    working_dir: /app
    command: bash -c "mix local.rebar --force && mix local.hex --force && tail -f /dev/null"

volumes:
  spear_eventstore:
